esphome:
  name: tv-amp
esp8266:
  board: esp07s

# Enable logging
logger:
  level: debug

# Secrets
api:
  encryption:
    key: !secret api_encryption_key
ota:
  password: !secret ota_password
wifi:
  fast_connect: true
  # output_power: 8.5db
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: TV-Amp-Controller
    password: !secret ap_password

output:
  - id: power_cycle
    platform: gpio
    pin: GPIO4
    inverted: true
binary_sensor:
  - id: power_state
    internal: true
    platform: gpio
    pin:
      number: GPIO5
      inverted: true
      mode:
        input: true
        pullup: true
button:
  - id: toggle_power
    internal: true
    platform: output
    output: power_cycle
    duration: 250ms
    on_press:
      then:
        delay: 250ms

switch:
  - id: power
    name: "Power"
    platform: template
    lambda: |-
      return id(power_state).state;
    turn_on_action:
    - if:
        condition:
          lambda: return !id(power_state).state;
        then:
          - button.press: toggle_power
    turn_off_action:
    - if:
        condition:
          lambda: return id(power_state).state;
        then:
          - button.press: toggle_power
